services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ragapi_db
    restart: always
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ragapi
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: ragapi_redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: